### ISSUE TITLE
Verbiage change

### ISSUE THREAD

**Issue by ericgomes56** [aquasecurity/aqua-aws#92]
Please change Select Yes to create a separate Manage RDS instance for Audit' to something like 'Select Yes if you have a separate AuditDB Endpoint' under Aqua Manage DB Configuration.

https://github.com/aquasecurity/aqua-aws/blob/6.0/cloudformation/aqua-ecs-ec2/aquaEcs-external.yaml
https://github.com/aquasecurity/aqua-aws/blob/6.0/cloudformation/aqua-ecs-fargate/ecs-fargate-nonSSL-external.yaml
https://github.com/aquasecurity/aqua-aws/blob/6.0/cloudformation/aqua-ecs-fargate/aquaFargate-external.yaml

**Comment by yossig-aquasec** [comment]
Done for branches 6.0 and 6.2
